In [17]:
import pandas as pd
student_data = {
    "Name": ["John", "Mary", "Steve", "Sarah", "David", "Anna"],
    "Age": [23, 13, 56, 34, 12, 41],
    "Maths": [90, 80, 70, 60, 50, 40],
    "English": [85, 75, 65, 55, 45, 35]
}
students = pd.DataFrame(student_data)
students

    Name  Age  Maths  English
0   John   23     90       85
1   Mary   13     80       75
2  Steve   56     70       65
3  Sarah   34     60       55
4  David   12     50       45
5   Anna   41     40       35

1. Find the average of english.

In [18]:
students["English"].mean()

np.float64(60.0)

The average of English is 60.0

2. Find the average of mathematics.

In [19]:
students["Maths"].mean()

np.float64(65.0)

The average of Maths is 65.0

3. Find the median age.

In [20]:
students["Age"].median()

np.float64(28.5)

The median age is 28.5

4. Find the median mark of Maths

In [21]:
students["Maths"].median()

np.float64(65.0)

The median mark of Maths is 65.0

5. Find the standard deviation for english.

In [22]:
students["English"].std()

np.float64(18.708286933869708)

The standard deviation of English is 18.708

6. What is the range of the age values in our data?

In [23]:
range = students["Age"].max() - students["Age"].min()
range

np.int64(44)

The range of the age values is 44

7. Which student scored the highest mark in English?

In [24]:
students.loc[students["English"].idxmax(), "Name"]

'John'

The student with the highest marks is John

8. Create a new column called total marks which is a combination of math and english marks and find the average of total marks.

In [25]:
students["Total_marks"] = students["Maths"] + students["English"]
students

    Name  Age  Maths  English  Total_marks
0   John   23     90       85          175
1   Mary   13     80       75          155
2  Steve   56     70       65          135
3  Sarah   34     60       55          115
4  David   12     50       45           95
5   Anna   41     40       35           75

The Total_marks column has been created with the values of [175,155,135,115,95,75]