In [375]:
import pandas as pd

In [376]:
data = {
    "Student" : ['Aisha', 'Brian', 'Cathy','Derek','Esther','Felix','Gloria','James','Annet','Daniel','Brenda','Oscar'],
    "Programme" : ['BSDS','BSCS','BSCS','BSIT','BSDS','BSCS','BSIT','BSDS','BSDS','BSCS','BSIT','BSDS'],
    "Sex" : ['F','M','F','M','F','M','F','M','F','M','F','M'],
    "StudyHours" : [18,8,22,6,20,12,14,10,24,7,9,16],
    "Attendance" : [92,60,95,55,90,70,80,65,98,58,62,85],
    "Score" : [78,45,88,39,83,61,66,52,91,44,48,72],
    "Result" : ['Pass','Fail','Pass','Fail','Pass','Pass','Pass','Pass','Pass','Fail','Fail','Pass'],
    "Scholarship" : ['Yes','No','Yes','No','Yes','No','No','No','Yes','No','No','Yes']
}
results_df = pd.DataFrame(data)
results_df

   Student Programme Sex  StudyHours  Attendance  Score Result Scholarship
0    Aisha      BSDS   F          18          92     78   Pass         Yes
1    Brian      BSCS   M           8          60     45   Fail          No
2    Cathy      BSCS   F          22          95     88   Pass         Yes
3    Derek      BSIT   M           6          55     39   Fail          No
4   Esther      BSDS   F          20          90     83   Pass         Yes
5    Felix      BSCS   M          12          70     61   Pass          No
6   Gloria      BSIT   F          14          80     66   Pass          No
7    James      BSDS   M          10          65     52   Pass          No
8    Annet      BSDS   F          24          98     91   Pass         Yes
9   Daniel      BSCS   M           7          58     44   Fail          No
10  Brenda      BSIT   F           9          62     48   Fail          No
11   Oscar      BSDS   M          16          85     72   Pass         Yes

The expected number of rows is 12 and expected number of columns is 8.

In [377]:
results_df.shape

(12, 8)

According to shape, the rows are 12 and the columns are 8.

In [378]:
results_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student      12 non-null     str
 1   Programme    12 non-null     str
 2   Sex          12 non-null     str
 3   StudyHours   12 non-null     int64
 4   Attendance   12 non-null     int64
 5   Score        12 non-null     int64
 6   Result       12 non-null     str
 7   Scholarship  12 non-null     str
dtypes: int64(3), str(5)
memory usage: 900.0 bytes

There are no missing values.

Columns are Student, Programme, Sex, Result, Scholarship and these are strings and StudyHours,Attendace and Score are integers.

In [379]:
results_df["StudyHours"].mean()

np.float64(13.833333333333334)

In [380]:
results_df["StudyHours"].median()

np.float64(13.0)

In [381]:
results_df["StudyHours"].std()

np.float64(6.132378054724008)

The mean,median and standard deviation of StudyHours are 13.83,13.0,6.13 respectively.

In [382]:
results_df["Attendance"].mean()

np.float64(75.83333333333333)

In [383]:
results_df["Attendance"].median()

np.float64(75.0)

In [384]:
results_df["Attendance"].std()

np.float64(15.862095088797714)

The mean,median and standard deviation of Attendance are 75.83,75.0 and 15.86 respectively.

In [385]:
results_df["Score"].mean()

np.float64(63.916666666666664)

In [386]:
results_df["Score"].median()

np.float64(63.5)

In [387]:
results_df["Score"].std()

np.float64(18.40186914089946)

The mean,median and standard deviation of Score are 63.92,63.5 and 18.40 respectively.

b)

In [388]:
max = results_df["Score"].max()
max

np.int64(91)

In [389]:
min = results_df["Score"].min()
min

np.int64(39)

In [390]:
max - min

np.int64(52)

In [391]:
results_df["Score"].quantile(0.25)

np.float64(47.25)

Q1 is 47.25

In [392]:
results_df["Score"].quantile(0.5)

np.float64(63.5)

Q2 is 63.5

In [393]:
results_df["Score"].quantile(0.75)

np.float64(79.25)

Q3 is 79.25

In [394]:
IQR = results_df["Score"].quantile(0.75) - results_df["Score"].quantile(0.25)
IQR

np.float64(32.0)

The interquartile range is 32.0

In [395]:
import numpy as np

In [396]:
percen = np.percentile(results_df["Score"], 90)
percen

np.float64(87.5)

In [397]:
outlier = 1.5 * IQR
outlier

np.float64(48.0)

In [398]:
results_df[results_df["Score"] == outlier]["Student"]

10    Brenda
Name: Student, dtype: str

The outlier is Brenda

In [399]:
results_df.describe()

       StudyHours  Attendance      Score
count   12.000000   12.000000  12.000000
mean    13.833333   75.833333  63.916667
std      6.132378   15.862095  18.401869
min      6.000000   55.000000  39.000000
25%      8.750000   61.500000  47.250000
50%     13.000000   75.000000  63.500000
75%     18.500000   90.500000  79.250000
max     24.000000   98.000000  91.000000

According to the mean and median, Score is symmetric

In [400]:
passed = results_df[results_df["Result"] == "Pass"]
passed

   Student Programme Sex  StudyHours  Attendance  Score Result Scholarship
0    Aisha      BSDS   F          18          92     78   Pass         Yes
2    Cathy      BSCS   F          22          95     88   Pass         Yes
4   Esther      BSDS   F          20          90     83   Pass         Yes
5    Felix      BSCS   M          12          70     61   Pass          No
6   Gloria      BSIT   F          14          80     66   Pass          No
7    James      BSDS   M          10          65     52   Pass          No
8    Annet      BSDS   F          24          98     91   Pass         Yes
11   Oscar      BSDS   M          16          85     72   Pass         Yes

In [401]:
pass_study = passed["StudyHours"].mean()
pass_study

np.float64(17.0)

In [402]:
pass_attend = passed["Attendance"].mean()
pass_attend

np.float64(84.375)

In [403]:
fail = results_df[results_df["Result"] == "Fail"]
fail

   Student Programme Sex  StudyHours  Attendance  Score Result Scholarship
1    Brian      BSCS   M           8          60     45   Fail          No
3    Derek      BSIT   M           6          55     39   Fail          No
9   Daniel      BSCS   M           7          58     44   Fail          No
10  Brenda      BSIT   F           9          62     48   Fail          No

In [404]:
fail_study = fail["StudyHours"].mean()
fail_study

np.float64(7.5)

In [405]:
fail_attend = fail["Attendance"].mean()
fail_attend

np.float64(58.75)

In [406]:
study_gap = abs(pass_study - fail_study)
study_gap

np.float64(9.5)

In [407]:
attend_gap = abs(pass_attend - fail_attend)
attend_gap

np.float64(25.625)

In [408]:
if study_gap > attend_gap:
    print("StudyHours shows a larger gap")
elif attend_gap > study_gap:
    print("Attendance shows a larger gap")
else:
    print("Both factors have the same gap")

Attendance shows a larger gap

Attendance shows a larger gap

part e)

Attendance because the values have the largest deviation and a larger gap in the students that passed and the students that failed. It isn't advised to look at only 12 students because those results do not represent the students in general and a larger dataset would give more reliable conclusions.

In [409]:
data2 = pd.read_csv("penguins.csv")
data2

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [410]:
data3 = data2.dropna()
data3

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [411]:
data2.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [412]:
data3.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE

In [413]:
data3.shape

(333, 7)

In [414]:
data2.shape

(344, 7)

In [415]:
data3["bill_length_mm"].mean()

np.float64(43.99279279279279)

In [416]:
data3["bill_depth_mm"].median()

np.float64(17.3)

In [417]:
data3["bill_depth_mm"].mode()

0    17.0
Name: bill_depth_mm, dtype: float64

In [418]:
data3["bill_depth_mm"].std()

np.float64(1.9692354633199007)

In [419]:
data3["flipper_length_mm"].median()

np.float64(197.0)

In [420]:
data3["body_mass_g"].mean()

np.float64(4207.057057057057)

In [421]:
data3["body_mass_g"].median()

np.float64(4050.0)

In [422]:
data3["flipper_length_mm"].mean()

np.float64(200.96696696696696)

In [423]:
data3["flipper_length_mm"].std()

np.float64(14.015765288287879)

In [424]:
data3["body_mass_g"].std()

np.float64(805.2158019428965)

In [425]:
Q1 = data3["body_mass_g"].quantile(0.25)
Q1

np.float64(3550.0)

In [426]:
Q3 = data3["body_mass_g"].quantile(0.75)
Q3

np.float64(4775.0)

In [427]:
IQR = Q3 - Q1
IQR

np.float64(1225.0)

In [428]:
outlier2 = 1.5 * IQR
outlier2

np.float64(1837.5)

In [429]:
lower_boundary = Q1 - 1.5 * IQR
lower_boundary

np.float64(1712.5)

In [430]:
upper_boundary = Q3 + 1.5 * IQR
upper_boundary

np.float64(6612.5)

In [431]:

def find_outliers(group):
    Q1 = group["body_mass_g"].quantile(0.25)
    Q3 = group["body_mass_g"].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outliers = group[(group["body_mass_g"] < lower) |
                     (group["body_mass_g"] > upper)]
    
    return pd.Series({
        "IQR": IQR,
        "Number of Outliers": len(outliers)
    })

result = data3.groupby("species").apply(find_outliers)

print(result)

             IQR  Number of Outliers
species
Adelie     637.5                 0.0
Chinstrap  462.5                 2.0
Gentoo     800.0                 0.0

In [432]:
columns = ["body_mass_g","bill_length_mm", "flipper_length_mm",]

summary = pd.DataFrame({
    "Mean" : data3[columns].mean(),
    "Median" : data3[columns].median(),
    "Mode" : data3[columns].mode().iloc[0],
    "Standard Deviation" : data3[columns].std(),
    "IQR" : data3[columns].quantile(0.75) - data3[columns].quantile(0.25)
})
summary

                          Mean  Median    Mode  Standard Deviation     IQR
body_mass_g        4207.057057  4050.0  3800.0          805.215802  1225.0
bill_length_mm       43.992793    44.5    41.1            5.468668     9.1
flipper_length_mm   200.966967   197.0   190.0           14.015765    23.0

In [433]:
longest_flippers_on_average = summary["Mean"].idxmax()
longest_flippers_on_average

'body_mass_g'

In [434]:
largest_std = summary["Standard Deviation"].idxmax()
largest_std

'body_mass_g'

In [435]:
import numpy as np

In [436]:
#np.percentile(data3["body_mass_g"],90)
percentile_90 = data3["body_mass_g"].quantile(0.90)
percentile_90

np.float64(5440.000000000001)

penguins with higher body mass than 90th percentile

In [437]:
count = (data3["body_mass_g"] > percentile_90 ).sum()    #the condition returns True or False and .sum() counts the True values
print("Number of penguins weighing more than the 90th percentile:", count)

Number of penguins weighing more than the 90th percentile: 34

In [438]:
np.percentile(data3["body_mass_g"], 10)

np.float64(3300.0)

In [439]:
np.percentile(data3["body_mass_g"], 25)

np.float64(3550.0)

In [440]:
np.percentile(data3["body_mass_g"], 50)

np.float64(4050.0)

In [441]:
np.percentile(data3["body_mass_g"], 75)

np.float64(4775.0)

In [442]:
data3["species"]

0      Adelie
1      Adelie
2      Adelie
4      Adelie
5      Adelie
        ...
338    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 333, dtype: str

In [443]:
spe = data3[data3["species"] == "Adelie"]["flipper_length_mm"]
one = spe.mean()
one

np.float64(190.1027397260274)

In [444]:
two = spe.std()
two

np.float64(6.521824847286749)

In [445]:
three = spe.quantile(0.75) - spe.quantile(0.25)
three

np.float64(9.0)

In [446]:
spe1 = data3[data3["species"] == "Gentoo"]["flipper_length_mm"]
four = spe1.mean()
four

np.float64(217.23529411764707)

In [447]:
summary1 = data3.groupby("species")["flipper_length_mm"].agg(
    Mean="mean",
    Standard_Deviation="std",
    Range=lambda x: x.max() - x.min()
)
summary1

                 Mean  Standard_Deviation  Range
species
Adelie     190.102740            6.521825   38.0
Chinstrap  195.823529            7.131894   34.0
Gentoo     217.235294            6.585431   28.0